// CertificationPanel — chief-auditor co-signed Review Attestation.
//
// Terminology note (per AiGovOps Foundation alignment, April 2026):
//   - "Review Attestation" = the signed PDF this panel produces (QAGA / chief-auditor
//     conformance statement against AOS). What this file calls a "compliance certification"
//     is the same artifact — UI labels prefer "Review Attestation" externally.
//   - "Control Evidence" = the upstream artifacts an organization produces showing
//     individual controls actually ran (audit log entries, test results, signed contracts).
// Auto-generated by the pipeline on non-fail verdicts; user can re-issue manually
// from this panel at any time.
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { ShieldCheck, Loader2, Download, ExternalLink, Sparkles } from "lucide-react";

const SUPABASE_URL = `https://${import.meta.env.VITE_SUPABASE_PROJECT_ID}.supabase.co`;

interface CertRow {
  id: string;
  determination: string;
  organization: string;
  scope_statement: string;
  pdf_path: string | null;
  pdf_sha256: string | null;
  ken_signature: string | null;
  bob_signature: string | null;
  signature_kind: string;
  trigger_kind: string;
  audit_entry_hash: string | null;
  issued_at: string;
}

const verdictTone: Record<string, string> = {
  pass: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30",
  pass_with_compensations: "bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30",
  fail: "bg-destructive/15 text-destructive border-destructive/30",
};

export const CertificationPanel = ({ reviewId }: { reviewId: string }) => {
  const [certs, setCerts] = useState<CertRow[]>([]);
  const [busy, setBusy] = useState(false);
  const [org, setOrg] = useState("");
  const [scope, setScope] = useState("");

  const load = async () => {
    const { data } = await supabase
      .from("certifications")
      .select("id, determination, organization, scope_statement, pdf_path, pdf_sha256, ken_signature, bob_signature, signature_kind, trigger_kind, audit_entry_hash, issued_at")
      .eq("review_id", reviewId)
      .order("issued_at", { ascending: false });
    setCerts((data ?? []) as CertRow[]);
    if (data?.[0]) {
      setOrg((prev) => prev || data[0].organization);
      setScope((prev) => prev || data[0].scope_statement);
    }
  };
  useEffect(() => { load(); }, [reviewId]);

  const issue = async () => {
    setBusy(true);
    const { data, error } = await supabase.functions.invoke("issue-certification", {
      body: { reviewId, organization: org.trim() || undefined, scopeStatement: scope.trim() || undefined, trigger: "manual" },
    });
    setBusy(false);
    if (error || (data && (data as { error?: string }).error)) {
      toast.error(error?.message ?? (data as { error?: string })?.error ?? "Certification failed");
      return;
    }
    toast.success("Compliance certification issued · co-signed by Ken & Bob");
    load();
  };

  return (
    <div className="space-y-4">
      <div className="rounded-lg border border-border bg-card-grad p-4 space-y-3">
        <div className="text-sm font-medium flex items-center gap-2">
          <ShieldCheck className="h-4 w-4 text-primary" />
          {certs.length ? "Re-issue compliance certification" : "Issue compliance certification"}
        </div>
        <p className="text-xs text-muted-foreground">
          Co-signed by Ken "The Chief" Newton and Bob "Fair Witness" Smith. Includes a chain-of-custody manifest of every audit log entry for this review and is anchored into the HMAC audit chain.
        </p>
        <Input
          placeholder="Organization (defaults to your profile org)"
          value={org}
          onChange={(e) => setOrg(e.target.value)}
        />
        <Textarea
          placeholder="Scope statement (defaults to the review title)"
          rows={2}
          value={scope}
          onChange={(e) => setScope(e.target.value)}
        />
        <Button onClick={issue} disabled={busy} size="sm">
          {busy ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Sparkles className="h-4 w-4 mr-1.5" />}
          {certs.length ? "Re-issue attestation" : "Issue attestation"}
        </Button>
      </div>

      {certs.map((cert) => {
        const pdfUrl = cert.pdf_path
          ? `${SUPABASE_URL}/storage/v1/object/public/attestations/${cert.pdf_path}`
          : null;
        const verifyUrl = `${window.location.origin}/verify/${reviewId}`;
        return (
          <div key={cert.id} className="rounded-lg border border-border bg-card-grad p-4 space-y-3">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-2 flex-wrap">
                <Badge variant="outline" className={verdictTone[cert.determination] ?? ""}>
                  {cert.determination.replace(/_/g, " ")}
                </Badge>
                <Badge variant="outline" className="font-mono text-[10px]">
                  {cert.trigger_kind === "auto" ? "auto" : "manual"}
                </Badge>
                <Badge variant="outline" className="font-mono text-[10px]">{cert.signature_kind}</Badge>
                <span className="text-xs text-muted-foreground">{new Date(cert.issued_at).toLocaleString()}</span>
              </div>
              <div className="flex gap-2">
                {pdfUrl && (
                  <Button asChild variant="outline" size="sm">
                    <a href={pdfUrl} target="_blank" rel="noreferrer">
                      <Download className="h-4 w-4 mr-1.5" />PDF
                    </a>
                  </Button>
                )}
                <Button asChild variant="outline" size="sm">
                  <a href={verifyUrl} target="_blank" rel="noreferrer">
                    <ExternalLink className="h-4 w-4 mr-1.5" />Verify
                  </a>
                </Button>
              </div>
            </div>
            <div className="space-y-1 text-[11px] font-mono text-muted-foreground break-all">
              {cert.pdf_sha256 && <div>pdf sha256: {cert.pdf_sha256}</div>}
              {cert.audit_entry_hash && <div>audit anchor: {cert.audit_entry_hash}</div>}
              {cert.ken_signature && <div>Ken sig: {cert.ken_signature.slice(0, 32)}…</div>}
              {cert.bob_signature && <div>Bob sig: {cert.bob_signature.slice(0, 32)}…</div>}
            </div>
            <p className="text-[10px] text-muted-foreground italic">
              Demonstration HMAC-SHA256 signatures · Ed25519 upgrade pending.
            </p>
          </div>
        );
      })}

      {!certs.length && (
        <div className="rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">
          No Review Attestation issued yet. The Quick Audit pipeline auto-issues one on a non-fail
          verdict, or click <strong>Issue attestation</strong> above.
        </div>
      )}
    </div>
  );
};
