
-- ============= AOS Versions & Control Catalog =============
CREATE TABLE IF NOT EXISTS public.aos_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'draft',  -- draft | active | retired
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.aos_controls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id uuid NOT NULL REFERENCES public.aos_versions(id) ON DELETE CASCADE,
  control_id text NOT NULL,           -- e.g. AOS-L1-01
  level int NOT NULL DEFAULT 1,
  domain text NOT NULL,               -- pipeline | evidence | decisioning | safety | data | model | ops
  objective text NOT NULL,            -- what the control achieves
  testing_procedure text NOT NULL,    -- how an assessor tests it
  evidence_expected text NOT NULL,    -- what evidence the pipeline must produce
  framework_refs text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, control_id)
);

ALTER TABLE public.aos_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aos_controls ENABLE ROW LEVEL SECURITY;

-- Public catalog: anyone can read
CREATE POLICY "aos_versions readable by all"
  ON public.aos_versions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "aos_controls readable by all"
  ON public.aos_controls FOR SELECT TO anon, authenticated USING (true);
-- Only admins manage
CREATE POLICY "admins manage aos_versions"
  ON public.aos_versions FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "admins manage aos_controls"
  ON public.aos_controls FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

-- Helper to get active version id
CREATE OR REPLACE FUNCTION public.aos_active_version()
RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM public.aos_versions WHERE status='active' ORDER BY created_at DESC LIMIT 1
$$;

-- Seed v0.1-draft as ACTIVE (clearly marked unofficial)
INSERT INTO public.aos_versions (version, status, notes)
VALUES ('0.1-draft', 'active',
'UNOFFICIAL working seed catalog generated by the AiGovOps Review Framework for prototyping. Replace with the AiGovOps Foundation''s published AOS v0.1 Level 1 controls before any QAGA-signed attestations are issued.')
ON CONFLICT (version) DO NOTHING;

-- Seed Level 1 controls
WITH v AS (SELECT id FROM public.aos_versions WHERE version='0.1-draft')
INSERT INTO public.aos_controls (version_id, control_id, level, domain, objective, testing_procedure, evidence_expected, framework_refs)
SELECT v.id, x.control_id, 1, x.domain, x.objective, x.testing_procedure, x.evidence_expected, x.framework_refs
FROM v, (VALUES
  ('AOS-L1-01','pipeline','Every AI deployment is governed by versioned policy-as-code.','Confirm policy bundle is committed to a tracked repo with semver and signed tags.','Repo URL, commit SHA, signed tag, policy file checksums.', ARRAY['NIST AI RMF GOVERN-1.4','ISO 42001 6.2']),
  ('AOS-L1-02','pipeline','Policy bundle has package, version, owner, and description metadata.','Lint the bundle for required metadata fields.','Lint report showing all required fields present.', ARRAY['ISO 42001 7.5']),
  ('AOS-L1-03','pipeline','No policy contains an unsafe default-allow rule.','Static-scan all rules for `default allow = true` or equivalent.','Scanner output with zero unsafe defaults.', ARRAY['NIST AI RMF MANAGE-2.1']),
  ('AOS-L1-04','pipeline','All controls run automatically in CI on every change.','Inspect CI configuration for AOS gate; trigger a synthetic violation and confirm CI fails.','CI run logs, gate config, synthetic-failure run.', ARRAY['NIST AI RMF MEASURE-3','SOC 2 CC8.1']),
  ('AOS-L1-05','evidence','Every agent run produces an evidence artifact stored append-only.','Sample 10 runs from the audit log and confirm evidence rows exist with content hash.','Audit log entries with payload + content hash.', ARRAY['ISO 42001 9.1','NIST AI RMF MEASURE-4.2']),
  ('AOS-L1-06','evidence','Audit entries are cryptographically chained (HMAC) and tamper-evident.','Run chain verifier on the full review history; expect zero invalid entries.','Verifier output, HMAC algorithm doc, key custody statement.', ARRAY['NIST AI RMF GOVERN-4.1','ISO 27001 A.12.4']),
  ('AOS-L1-07','evidence','Evidence retention period is documented and enforced.','Inspect retention policy; query age of oldest record.','Retention policy doc, db query showing oldest entry.', ARRAY['EU AI Act Art. 12','HIPAA §164.316(b)(2)']),
  ('AOS-L1-08','decisioning','Every consequential AI decision logs inputs, outputs, model id, and policy version.','Trace 5 production decisions through the log; confirm all four fields present.','Decision logs with model id + policy version.', ARRAY['EU AI Act Art. 13','NIST AI RMF MEASURE-2.7']),
  ('AOS-L1-09','decisioning','A human override path exists and is exercised at least quarterly.','Inspect override interface + quarterly drill records.','Override UI screenshot, drill log, ticket.', ARRAY['EU AI Act Art. 14','NIST AI RMF MANAGE-1.3']),
  ('AOS-L1-10','decisioning','Human reviewers are authenticated and roles are separated from developers.','Confirm RBAC config; reviewer cannot deploy code.','RBAC export, deployment ACLs.', ARRAY['SOC 2 CC6.3','ISO 27001 A.5.3']),
  ('AOS-L1-11','safety','Red-team / adversarial tests run in CI and block release on regression.','Inspect red-team CI step + last 10 runs.','Red-team test suite, CI logs, regression policy.', ARRAY['NIST AI RMF MEASURE-2.6']),
  ('AOS-L1-12','safety','High-risk scenarios (healthcare, IP, HR) have scenario-specific control packs.','Confirm scenario tag → control pack mapping is enforced at submission.','Scenario rule pack manifest + enforcement test.', ARRAY['EU AI Act Annex III']),
  ('AOS-L1-13','data','Training and inference data lineage is recorded and queryable.','Pick 3 model versions; produce upstream data sources.','Lineage graph, dataset checksums.', ARRAY['EU AI Act Art. 10','ISO 42001 8.3']),
  ('AOS-L1-14','data','Personally identifiable / regulated data is classified and minimized.','Inspect data classification labels and minimization transforms.','Classification report, minimization config.', ARRAY['GDPR Art. 5(1)(c)','HIPAA §164.502(b)']),
  ('AOS-L1-15','model','Each released model has a machine-readable model card captured at build time.','Pull model cards for last 3 releases.','Model card JSON in evidence store.', ARRAY['NIST AI RMF MAP-3','ISO 42001 8.4']),
  ('AOS-L1-16','model','Generated content for IP claims has provenance metadata (C2PA or equivalent).','Sample 5 generated artifacts; verify embedded provenance.','C2PA manifests, signature chain.', ARRAY['DMCA','EU AI Act Art. 50']),
  ('AOS-L1-17','ops','Open-source AI dependencies have SBOM + license + provenance attestations.','Inspect SBOM and SLSA attestations for top 10 deps.','SBOM (CycloneDX), SLSA L2+ attestations.', ARRAY['NIST SSDF PO.5','EO 14028']),
  ('AOS-L1-18','ops','Incident response procedure is documented, drilled, and links to evidence chain.','Inspect IR runbook and last drill report.','IR runbook, drill report, post-mortem.', ARRAY['NIST AI RMF MANAGE-4','ISO 42001 10.1'])
) AS x(control_id, domain, objective, testing_procedure, evidence_expected, framework_refs)
ON CONFLICT (version_id, control_id) DO NOTHING;

-- ============= Tag findings with AOS control =============
ALTER TABLE public.agent_findings
  ADD COLUMN IF NOT EXISTS aos_control_id text,
  ADD COLUMN IF NOT EXISTS aos_version text;
CREATE INDEX IF NOT EXISTS idx_findings_aos_control ON public.agent_findings(aos_control_id);

-- ============= QAGAC Firms =============
CREATE TABLE IF NOT EXISTS public.qagac_firms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending',  -- pending | charter | active | suspended | revoked
  indemnity_carrier text,
  indemnity_amount_usd bigint,
  jurisdiction text,
  website text,
  contact_email text,
  public_listed boolean NOT NULL DEFAULT true,
  active_assessor_count int NOT NULL DEFAULT 0,
  charter_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_qagac_firms_touch BEFORE UPDATE ON public.qagac_firms
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
ALTER TABLE public.qagac_firms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "qagac public registry"
  ON public.qagac_firms FOR SELECT TO anon, authenticated
  USING (status IN ('charter','active') AND public_listed = true);
CREATE POLICY "qagac admins read all"
  ON public.qagac_firms FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "qagac admins manage"
  ON public.qagac_firms FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

-- A QAGAC's existing development/consulting engagements (used for independence checks)
CREATE TABLE IF NOT EXISTS public.firm_dev_engagements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  firm_id uuid NOT NULL REFERENCES public.qagac_firms(id) ON DELETE CASCADE,
  client_org text NOT NULL,            -- the org the firm did dev work for
  engagement_kind text NOT NULL,       -- design | development | implementation | mlops
  active_through timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firm_dev_client ON public.firm_dev_engagements(firm_id, client_org);
ALTER TABLE public.firm_dev_engagements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "firm dev engagements admin only"
  ON public.firm_dev_engagements FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

-- ============= QAGA Assessors =============
CREATE TABLE IF NOT EXISTS public.qaga_assessors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,        -- maps to auth user
  firm_id uuid REFERENCES public.qagac_firms(id) ON DELETE SET NULL,
  display_name text NOT NULL,
  jurisdiction text,
  -- Training/credential progression
  training_level text NOT NULL DEFAULT 'practitioner', -- practitioner | trainee | qaga
  training_completed_at timestamptz,
  exam_passed_at timestamptz,
  qaga_credential_id text UNIQUE,      -- assigned when level=qaga
  qaga_issued_at timestamptz,
  qaga_expires_at timestamptz,
  -- Adjacent (informational, not required)
  badges text[] NOT NULL DEFAULT '{}', -- ['AIGP','AAIA','CISA','CISM','CISSP']
  status text NOT NULL DEFAULT 'active', -- active | suspended | revoked
  public_listed boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_qaga_assessors_touch BEFORE UPDATE ON public.qaga_assessors
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
ALTER TABLE public.qaga_assessors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "assessors public registry"
  ON public.qaga_assessors FOR SELECT TO anon, authenticated
  USING (training_level='qaga' AND status='active' AND public_listed=true);
CREATE POLICY "assessors read self or admin"
  ON public.qaga_assessors FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY "assessors admin manage"
  ON public.qaga_assessors FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "assessors self update training progression"
  ON public.qaga_assessors FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid() AND training_level <> 'qaga'); -- can't self-promote to QAGA

-- ============= Engagements (assessor ↔ review with independence) =============
CREATE TABLE IF NOT EXISTS public.assessor_engagements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id uuid NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
  assessor_id uuid NOT NULL REFERENCES public.qaga_assessors(id) ON DELETE RESTRICT,
  firm_id uuid NOT NULL REFERENCES public.qagac_firms(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'requested', -- requested | declared | active | recused | completed
  client_org text NOT NULL,           -- the submitter's organization (snapshotted)
  independence_declared_at timestamptz,
  independence_signed_by uuid,        -- assessor user_id who signed
  independence_attestation text,      -- the text they affirmed
  conflict_reason text,               -- if recused
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (review_id, assessor_id)
);
CREATE TRIGGER trg_engagements_touch BEFORE UPDATE ON public.assessor_engagements
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
ALTER TABLE public.assessor_engagements ENABLE ROW LEVEL SECURITY;

-- Submitter sees engagements on their own reviews; assessor sees own; admin sees all
CREATE POLICY "engagements visibility"
  ON public.assessor_engagements FOR SELECT TO authenticated
  USING (
    public.has_role(auth.uid(),'admin')
    OR EXISTS (SELECT 1 FROM public.qaga_assessors a WHERE a.id = assessor_engagements.assessor_id AND a.user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.reviews r WHERE r.id = assessor_engagements.review_id AND r.submitter_id = auth.uid())
  );
CREATE POLICY "engagements admin manage"
  ON public.assessor_engagements FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

-- ============= Engagement workflow functions =============

-- Request an engagement (admin assigns assessor to review).
-- Refuses if firm has a recorded dev engagement with the submitter org (Arthur Andersen rule).
CREATE OR REPLACE FUNCTION public.request_engagement(_review_id uuid, _assessor_id uuid)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _firm uuid;
  _client text;
  _conflict int;
  _eng_id uuid;
BEGIN
  IF NOT public.has_role(auth.uid(),'admin') THEN
    RAISE EXCEPTION 'admin only';
  END IF;

  SELECT firm_id INTO _firm FROM public.qaga_assessors
    WHERE id = _assessor_id AND status='active' AND training_level='qaga';
  IF _firm IS NULL THEN RAISE EXCEPTION 'assessor not active QAGA or has no firm'; END IF;

  -- Snapshot submitter org
  SELECT COALESCE(p.organization,'(unknown)') INTO _client
    FROM public.reviews r
    LEFT JOIN public.profiles p ON p.id = r.submitter_id
    WHERE r.id = _review_id;
  IF _client IS NULL THEN RAISE EXCEPTION 'review not found'; END IF;

  -- Independence check
  SELECT COUNT(*) INTO _conflict FROM public.firm_dev_engagements
    WHERE firm_id = _firm AND client_org = _client
      AND (active_through IS NULL OR active_through > now() - interval '12 months');
  IF _conflict > 0 THEN
    RAISE EXCEPTION 'independence conflict: firm has development engagement with client_org=%', _client;
  END IF;

  INSERT INTO public.assessor_engagements (review_id, assessor_id, firm_id, status, client_org)
  VALUES (_review_id, _assessor_id, _firm, 'requested', _client)
  RETURNING id INTO _eng_id;
  RETURN _eng_id;
END $$;

-- Assessor signs the independence declaration to activate.
CREATE OR REPLACE FUNCTION public.sign_independence_declaration(_engagement_id uuid, _attestation text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _user uuid := auth.uid();
  _ok boolean;
BEGIN
  SELECT EXISTS(SELECT 1 FROM public.assessor_engagements e
    JOIN public.qaga_assessors a ON a.id = e.assessor_id
    WHERE e.id = _engagement_id AND a.user_id = _user
  ) INTO _ok;
  IF NOT _ok THEN RAISE EXCEPTION 'not assigned to this engagement'; END IF;

  UPDATE public.assessor_engagements
  SET status = 'active',
      independence_declared_at = now(),
      independence_signed_by = _user,
      independence_attestation = _attestation
  WHERE id = _engagement_id;
END $$;

-- Maintain firm active assessor count
CREATE OR REPLACE FUNCTION public.recount_firm_assessors()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE public.qagac_firms f SET active_assessor_count = (
    SELECT COUNT(*) FROM public.qaga_assessors a
    WHERE a.firm_id = f.id AND a.training_level='qaga' AND a.status='active'
  ) WHERE f.id = COALESCE(NEW.firm_id, OLD.firm_id);
  RETURN NEW;
END $$;
CREATE TRIGGER trg_recount_firm_assessors
  AFTER INSERT OR UPDATE OR DELETE ON public.qaga_assessors
  FOR EACH ROW EXECUTE FUNCTION public.recount_firm_assessors();
